version: '3.3'

services:
  braindump:
    image: akim42003/braindump-all-in-one:0.5.3
    ports:
      - "1000:80"    # Frontend (nginx) - map port 1000 to container's port 80
      - "8001:8001"  # Backend API (if you need direct access)
    volumes:
      - braindump_data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  braindump_data: