version: '3.8'

services:
  frontend:
    image: akim42003/braindump-frontend:0.1.2
    ports:
      - "1000:80"
    depends_on:
      - backend
    restart: unless-stopped
  
  backend:
    image: akim42003/braindump-backend:0.1.0
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=braindump
      - DB_PORT=5432
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=braindump
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: