version: '3.3'

services:
  frontend:
    build: .
    ports:
      - "1000:80"
    depends_on:
      - backend
    restart: unless-stopped
    mem_limit: 256m
    cpus: 0.5
  
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.jetson
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=braindump
      - DB_PORT=5432
      - NODE_ENV=production
    restart: unless-stopped
    mem_limit: 512m
    cpus: 1.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=braindump
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    mem_limit: 1g
    cpus: 1.0
    command: ["postgres", "-c", "max_connections=50", "-c", "shared_buffers=128MB"]

volumes:
  postgres_data: