version: "3.3"

services:
  braindump-deployer:
    build:
      context: .
      dockerfile: Dockerfile.deployer
    container_name: braindump-deployer
    network_mode: host
    volumes:
      # Mount Docker socket for container management
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount current directory for compose files
      - .:/workspace:ro
    environment:
      - COMPOSE_FILE=docker-compose.prod.yml
      - ENV_FILE=backend/.env
    restart: unless-stopped
    depends_on: []

  # Health monitoring service (optional)
  deployer-monitor:
    image: alpine:3.18
    container_name: braindump-monitor
    network_mode: host
    command: >
      sh -c "
        while true; do
          echo '[MONITOR] Checking services...'
          if ! nc -z localhost 1000; then
            echo '[MONITOR] Frontend down'
          fi
          if ! nc -z localhost 3000; then
            echo '[MONITOR] Backend down'
          fi
          if ! nc -z localhost 5432; then
            echo '[MONITOR] Database down'
          fi
          sleep 60
        done
      "
    depends_on:
      - braindump-deployer
    restart: unless-stopped
    profiles:
      - monitoring
