version: '3.3'

services:
  braindump:
    image: akim42003/braindump-all-in-one:0.5.1
    ports:
      - "80:80"      # Frontend (nginx)
      - "3000:3000"  # Backend API
    volumes:
      - braindump_data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  braindump_data: